Fix for # 100 - Remove model library and access
epiverse-trace/epidemics pull request #130
Opened 2023-10-09 18:36 UTC by bahadzie

2023-10-10 08:29 UTC, pratikunterwegs commented
Thanks @bahadzie, I'll take a look today.

2023-10-16 09:19 UTC, pratikunterwegs commented
Hi @bahadzie, thanks for the PR - could you rebase it on `main` and resolve the merge conflict?

2023-10-25 12:42 UTC, pratikunterwegs requested changes
Thanks for this PR @bahadzie - I only have a few comments which I've left on the files. 

For future reference @amanda-minter had asked about where users might be able to find information on the models, including the compartment names, so I do think the model library is something we should reconsider in future; perhaps once there are more models.

2023-10-25 12:42 UTC, pratikunterwegs commented on .Rbuildignore
> +^.vscode$
```suggestion

```

2023-10-25 12:42 UTC, pratikunterwegs commented on .gitignore
> +.vscode
```suggestion

```

2023-10-25 12:42 UTC, pratikunterwegs commented on R/check_args_default.R
> +  compartments_default <- c("susceptible", "exposed", "infectious", "recovered", "vaccinated")
Could you fix these lintr notes?

2023-10-25 12:42 UTC, pratikunterwegs commented on R/check_args_ebola.R
> +  compartments_ebola <- c("susceptible", "exposed", "infectious", "recovered")
Could you update the ebola model compartment? There are six, with hospitalised and funeral transmission added in #110 - see the vignette for reference.

2023-10-25 12:42 UTC, pratikunterwegs commented on tests/testthat/test-ebola_model.R
> +    c("susceptible", "exposed", "infectious", "recovered")
Same comment as before about the new compartments

2023-10-25 12:42 UTC, pratikunterwegs commented on tests/testthat/test-epidemic_default.R
> +    compartments_default <- c("susceptible", "exposed", "infectious", "recovered", "vaccinated")
```suggestion
    c("susceptible", "exposed", "infectious", "recovered", "vaccinated")
```

2023-10-26 19:40 UTC, bahadzie commented on .Rbuildignore
> +^.vscode$
This was put there automatically by vscode, which is what I use instead of R Studio. 

Will it affect the package in any way if I leave it in my working folder without adding it to this file?

2023-10-26 19:40 UTC, bahadzie commented on .gitignore
> +.vscode
Same reason as comment above.

2023-10-26 20:33 UTC, bahadzie commented on R/check_args_default.R
> +  compartments_default <- c("susceptible", "exposed", "infectious", "recovered", "vaccinated")
Done

2023-10-26 20:34 UTC, bahadzie commented on tests/testthat/test-epidemic_default.R
> +    compartments_default <- c("susceptible", "exposed", "infectious", "recovered", "vaccinated")
Done

2023-10-26 22:00 UTC, bahadzie commented on R/check_args_ebola.R
> +  compartments_ebola <- c("susceptible", "exposed", "infectious", "recovered")
Done

2023-10-26 22:00 UTC, bahadzie commented on tests/testthat/test-ebola_model.R
> +    c("susceptible", "exposed", "infectious", "recovered")
Done

2023-10-27 08:51 UTC, pratikunterwegs commented on .Rbuildignore
> +^.vscode$
Not really no, I guess it can stay. I use vscode too but don't save a workspace - I guess these are your workspace settings?

2023-10-27 08:55 UTC, pratikunterwegs commented
Just a note on the last commit https://github.com/epiverse-trace/epidemics/pull/130/commits/9e55bee636bab06a2f6a7abd7cf7da04b34d8295 - we try to rebase on main so as not to have these update commits. Once checks pass, I'll squash-merge this PR rather than rebasing; more on [Epiverse merge strategy here in the Blueprints](https://epiverse-trace.github.io/blueprints/git-branching-merging.html#merging-pull-requests-merge-commits-vs-squash-and-merge-vs-rebase-and-merge).

2023-10-27 10:17 UTC, pratikunterwegs approved these changes
Thanks for fixing @bahadzie, looks good to me and squash-merging this now.

2023-10-27 10:19 UTC, merged