New API for ODE C++ models
epiverse-trace/epidemics pull request #176
Opened 2024-02-09 16:22 UTC by pratikunterwegs

This is a draft PR for awareness of substantial incoming changes; see #160 for reference.

2024-02-27 21:25 UTC, adamkucharski reviewed
This new vector options are looking good. Have focused comments on `modelling_scenarios.Rmd`, particularly around how to improve visibility/explanation  of new functionality for users, and giving some outputs that are close to what they'd want in practice (e.g. illustrative trajectories, tables of scenario comparison, estimation of infections averted). Also nice that single value inputs still return a data.frame rather than this getting more complex for users.

Note I had a query about the combined interventions for same parameter value in the final example – I might be missing something, but potentially a useful test to check that multiple interventions have more impact than single one for the same parameters in a deterministic model?

2024-02-27 21:25 UTC, adamkucharski commented on vignettes/modelling_scenarios.Rmd
> +labels <- c(
It could save users lots of time to have a helper function to automatically extract from the `intervention_scenarios` object, e.g.

```
extract_names <- function(scenario) {
  names <- sapply(scenario, function(x) x$name)
  paste(names, collapse = " + ")
}

labels <- sapply(intervention_scenarios, extract_names)
labels[names(labels)=="baseline"] <- "None"
```

Although have noticed that `combined_intervention` just pulls the name of the first one included. Perhaps neater for this vignette to define like the other combined scenarios? Unless I'm missing an easy way to grab both intervention names?

2024-02-27 21:25 UTC, adamkucharski commented on vignettes/modelling_scenarios.Rmd
> +combined_intervention <- c(close_schools, close_workplaces)
Should this be a list() rather than c() ? See below comment about extracting names – can't access the workplace values it seems.

2024-02-28 09:37 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +Generate 100 samples of $R$, and convert to the transmissibility parameter (often denoted $\beta$) by dividing by the infectious period of 7 days.
Thanks - I remember a P3 discussion about what to rename the parameters, but not why we settled on 'transmissibility' over 'transmission rate' - flagged for fixing as issue #186.

2024-02-28 09:39 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +filter(data, compartment == "infectious") %>%
Thanks - I think that's an artifact of how `stat_summary()` works - will fix, and would be worth adding to the visualisation guidelines.

2024-02-28 09:41 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +
Thanks, will add.

2024-02-28 09:48 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +Here, we show one way of visualising the epidemic size across scenarios, accounting for parameter uncertainty.
Thanks, will look into this - my initial assessment was that perhaps the workplace closure intervention wasn't having much of an effect, but agree that it should still have lower infections than a single intervention. Flagged for investigation and fixing in #187.

2024-02-28 09:54 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +combined_intervention <- c(close_schools, close_workplaces)
No, it should be `c()` as there's a method for `<contacts_intervention>` objects that ensures they are considered part of the same overall package of interventions on contacts.

The names of all but the first one are indeed discarded - but can be maintained as requested above.

2024-03-07 12:43 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +Here, we show one way of visualising the epidemic size across scenarios, accounting for parameter uncertainty.
Fixed in https://github.com/epiverse-trace/epidemics/pull/176/commits/7f690b082e7ed51624484cf7f5c79097f3d7b6a0 and https://github.com/epiverse-trace/epidemics/pull/176/commits/23ed308cd631e1e4c9ee27273cbceb9d9b68ed18; more discussion is in #187.

2024-03-07 12:44 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +
Fixed in https://github.com/epiverse-trace/epidemics/pull/176/commits/7f690b082e7ed51624484cf7f5c79097f3d7b6a0 by adding an output data.frame (to avoid dependency on {kable}).

2024-03-07 12:48 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +filter(data, compartment == "infectious") %>%
Fixed in https://github.com/epiverse-trace/epidemics/pull/176/commits/7f690b082e7ed51624484cf7f5c79097f3d7b6a0 with similar plot as previous version.

2024-03-07 12:48 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +The output is a nested `<data.table>`, with the output of each run of the model for each unique `transmissibility` contained as a `<data.frame>` in the list column `"data"`.
Added in https://github.com/epiverse-trace/epidemics/pull/176/commits/7f690b082e7ed51624484cf7f5c79097f3d7b6a0

2024-03-07 12:49 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +Generate 100 samples of $R$, and convert to the transmissibility parameter (often denoted $\beta$) by dividing by the infectious period of 7 days.
I'm moving this fix to a [later project](https://github.com/orgs/epiverse-trace/projects/37) but do say if this is a priority change.

2024-03-07 12:51 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +# calculate the epidemic size to plot a distribution of sizes
I've shifted to using the {magrittr} pipe throughout in https://github.com/orgs/epiverse-trace/projects/37, as the base pipe is dependent on the R version.

2024-03-07 13:10 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +labels <- c(
Flagging this for fixing in #189, but won't be in this PR as it's already quite large.

2024-03-08 15:46 UTC, jamesmbaazam commented on R/check_args_diphtheria.R
> +  # assign initial state; note prop_vaccinated have been removed
When was `prop_vaccinated` removed?

2024-03-08 15:49 UTC, pratikunterwegs commented on R/check_args_diphtheria.R
> +  # assign initial state; note prop_vaccinated have been removed
It's a confusing comment, I now see - `prop_vaccinated` have been removed from the `susceptible` compartment. Can make it clearer.

2024-03-08 16:44 UTC, jamesmbaazam commented on R/model_diphtheria.R
>    )
I understand what it's doing technically but not sure of the broader picture. It is quite dense and would read better in smaller chunks with reason-style comments.

2024-03-08 16:45 UTC, jamesmbaazam commented on R/model_diphtheria.R
> +  # Check if parameters can be recycled;
Is this comment supposed to go on L232?

2024-03-08 16:46 UTC, jamesmbaazam commented on R/model_diphtheria.R
> +  is_lofints <- checkmate::test_list(
Took me a while to figure out what the name means. Could you maybe write it in full, i.e., `is_list_of_interventions`?

2024-03-08 16:47 UTC, jamesmbaazam commented on R/model_diphtheria.R
> +  is_lofls <- checkmate::test_list(
Please see my previous comment about the object name being hard to figure out.

2024-03-08 17:03 UTC, jamesmbaazam commented on R/model_diphtheria.R
> +#' @return A `data.frame` with the columns "time", "compartment", "age_group",
Return is a `data.table`.

2024-03-08 17:17 UTC, jamesmbaazam commented on R/model_vacamole.R
>    )
Please refer to my previous comment on object naming and dense code blocks that are hard to digest at a glance.

2024-03-08 17:20 UTC, jamesmbaazam commented on R/model_vacamole.R
> +  )
I think this might be checked in another model I saw previously. Could this be bundled up into a function to be reused in more than one place?

2024-03-08 17:21 UTC, jamesmbaazam commented on R/model_vacamole.R
> +  }
I think this can be bundled up too since it's done in other models as well.

2024-03-08 17:22 UTC, jamesmbaazam commented on R/model_vacamole.R
>    )
Another opportunity for bundling into a function for reuse?

2024-03-08 17:23 UTC, jamesmbaazam commented on R/model_vacamole.R
> +  })]
Another opportunity to throw this in a function for reuse?

2024-03-08 17:35 UTC, jamesmbaazam commented on R/tools.R
> +    no_vaccination(population, doses = doses)
Should `.no_vaccination()` use a dot prefix for consistency?

2024-03-08 17:54 UTC, jamesmbaazam commented on vignettes/modelling_scenarios.Rmd
> +Since _EpiEstim_ estimates $Rt$, the real-time $R$, we shall use the mean of the estimates over the time period, and the mean of the standard deviation, as parameters for a distribution from which to
I think `EpiEstim` estimates the instantaneous/retrospective Rt, not the real-time one right?

2024-03-08 17:55 UTC, jamesmbaazam commented on vignettes/modelling_scenarios.Rmd
> +# pass the vector of transmissibilities to the argument `transmissibility`
Really nice!!

2024-03-08 17:59 UTC, jamesmbaazam commented on vignettes/modelling_scenarios.Rmd
> +2. All but one infection parameter must be scalar values (single numbers). This is the worked-out example shown above.
Can this be simplified to "Only one can be a vector" for people like me who struggle to process sentences like "all but one"? :(.

2024-03-08 18:02 UTC, jamesmbaazam commented on vignettes/modelling_scenarios.Rmd
> +duration <- max_time - with_seed(seed = 1, {
Do you maybe want to only use the unique values and also sort them before passing to next step? (not strictly necessary to sort but good on the eye). Could you perhaps also print them?

2024-03-08 18:03 UTC, jamesmbaazam commented on vignettes/modelling_scenarios.Rmd
> +    size = map_dbl(data, epidemic_size, by_group = FALSE)
You could also demonstrate the by_group version here.

2024-03-08 18:07 UTC, jamesmbaazam commented on vignettes/modelling_scenarios.Rmd
> +It is not possible to pass lists of _populations_, _seasonality_, or _population changes_ (for the diphtheria model).
Could this be expanded to state the reason or whether there are plans for this in the future?

2024-03-08 18:13 UTC, jamesmbaazam commented on vignettes/modelling_scenarios.Rmd
> +## Modelling scenarios of epidemic response
I feel like this point onwards should be a separate vignette because it can get a bit overwhelming to read one long vignette vs multiple smaller vignettes but I'll leave that to your discretion.

2024-03-08 18:30 UTC, jamesmbaazam requested changes
# Review of new vectorised interface to {epidemics}

Really neat enhancement to {epidemics}, @pratikunterwegs. The new changes make {epidemics} robust to the needs of routine compartmental modelling use cases. I really like the examples demonstrated in the new "modelling scenarios" vignette. 

I have left some line comments suggesting ways to improve the code. I am also leaving other comments below where I couldn't leave line comments. 

## Other comments
 
* In `.check_prepare_args_default()`, lots of subsetting are done in a pattern
that could potentially be turned into helper functions. Can subsetting
operations like `mod_args[["vaccination"]][["time_begin"]]` be combined into a
subsetting function that take an "intervention" and "element" argument? 
This would reduce the hardcoding of the list elements and make the code more
readable and maintainable.

* Can the details section of all the `check_args_*()` functions be combined
into a single template? They seem to be quite similar and repeated and might be
easier to maintain if turned into one.

* Can the `R/dummy_elements.R` script be renamed to something more descriptive?
The `no_time_dependence()` function could be moved to the `time_dependence.R`
script and the `no_population_change()` function moved somewhere with related
content. This will make it easier to find the functions when needed.

* `output_to_df()` should probably be renamed to `output_to_dt()` since it
returns a `data.table`. The `return` value should also be changed from
`data.frame` to `data.table` to reflect the code.

* `epidemic_size()`:
  - The return value needs to be updated to say it returns a `data.table`.
  - Could you enhance it to return the epidemic size by a selection of age
  groups?
  - Could you return the "stage" as part of the output? I can easily imagine
  that being useful in cases where a user wants to plot the epidemic size at
  various stages of the outbreak.
  - I would suggest renaming "stage" to timepoint or something similar and
  filter by time instead of stage. We often think of epidemic timelines in
  terms of dates and not stages. Using stages forces you to think in terms of
  percentages of the whole timeline. Additionally, you could make "stage" an
  optional argument alongside the new "time" argument.

* I see `get_parameter()` has been removed but I see the replaced subsetting
operations are identical to what `get_parameter()` would do. Why was it
removed instead of being updated to do the new list subsetting? Could you
convert all the `x$<some element>` into a getter function like `get_parameter()`
previously? This would make the code more readable.

* Is the term "demography_vector" chosen for any reason? I think in the contexts
it's used here, it mostly refers to the population size per age group.
Could you rename it to some like "group_pop_size" or something similar since
demography is too broad a term?

* Can `population_change` in `model_diphtheria()` be structured in a manner
to take a time series of population changes? For example, I might want to
model a population change that occurs at a certain time point and then another
change that occurs at a later time point. This would allow for more flexibility
in the model.

* Can `model_vacamole()` be renamed to `model_covid19()` or something
descriptive so as to align with the other models named after the disease they
represent? I can understand if you're trying to use the original
name to conserve the credit (or maybe I'm not privy to the reuse agreement)
but credit can be given in the function documentation and README as is currently
done.

* I would suggest doing the input checks outside of the `model_*()` functions
to make the code more focused on the model rather than being overpowered with
input checks.

Please feel free to engage with me where you need more clarification or brainstorming and also feel free to take or leave my suggestions.

2024-03-11 10:08 UTC, pratikunterwegs commented on R/model_vacamole.R
> +  )
Do you mean the whole chunk of input checking? I agree it's pretty similar across models, but I think it's good to keep it here because the models could vary in future, which would make a potential general input checking function more complicated for only a few use cases. For example, some models don't allow vaccination, or contacts interventions, and the function would have to accommodate these variations.

2024-03-11 10:19 UTC, pratikunterwegs commented on R/model_vacamole.R
> +  }
Bundling this up, say, to return a list of lists (of composable elements) would I reckon make it more difficult to create combinations later using `data.table::CJ()` - there, I would have to deconstruct the returned list again. A small reprex to show how; the second example is what I'm going for.

``` r
library(data.table)
l = list(a = list(1, 2, 3), b = list(1, 2, 3))
d = c(1, 2, 3)
CJ(l, d = d, sorted = FALSE)
#>            l     d
#>       <list> <num>
#> 1: <list[3]>     1
#> 2: <list[3]>     2
#> 3: <list[3]>     3
#> 4: <list[3]>     1
#> 5: <list[3]>     2
#> 6: <list[3]>     3

CJ(a = list(1,2,3), b = list(1,2,3), d, sorted = FALSE)
#>          a      b     d
#>     <list> <list> <num>
#>  1:      1      1     1
#>  2:      1      1     2
#>  3:      1      1     3
#>  4:      1      2     1
#>  5:      1      2     2
#>  6:      1      2     3
#>  7:      1      3     1
#>  8:      1      3     2
#>  9:      1      3     3
#> 10:      2      1     1
#> 11:      2      1     2
#> 12:      2      1     3
#> 13:      2      2     1
#> 14:      2      2     2
#> 15:      2      2     3
#> 16:      2      3     1
#> 17:      2      3     2
#> 18:      2      3     3
#> 19:      3      1     1
#> 20:      3      1     2
#> 21:      3      1     3
#> 22:      3      2     1
#> 23:      3      2     2
#> 24:      3      2     3
#> 25:      3      3     1
#> 26:      3      3     2
#> 27:      3      3     3
#>          a      b     d
```

<sup>Created on 2024-03-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Here, I would

2024-03-11 11:19 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +duration <- max_time - with_seed(seed = 1, {
> Do you maybe want to only use the unique values and also sort them before passing to next step? 

The idea is to show how epidemic size by a fixed end date varies due to uncertainty in the start date (and hence the duration), so any non-unique values would have to be retained.

> Could you perhaps also print them?

Sure.

2024-03-11 11:37 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +It is not possible to pass lists of _populations_, _seasonality_, or _population changes_ (for the diphtheria model).
Yes, it's in the next line - I do plan to allow list input to `population`; that's issue #181.

2024-03-11 11:38 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +In future, it may be possible to pass multiple populations as a list, to rapidly and conveniently model an epidemic on different populations, or to examine the effect of assumptions about the populat
Agreed, if you have any input or use-cases you could add them to the comments on #181. This isn't planned until after the vectorisation of the Ebola model, but if needed can be brought forward.

2024-03-11 11:38 UTC, jamesmbaazam commented on vignettes/modelling_scenarios.Rmd
> +duration <- max_time - with_seed(seed = 1, {
I get the idea but duplicate start dates will return the same results. Am I wrong?

2024-03-11 11:43 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +duration <- max_time - with_seed(seed = 1, {
Indeed, but retaining those would be necessary to get a correct distribution of final sizes. E.g. if most epidemics have a duration of exactly X days, the final size distribution's central tendency should be towards the final size for an epidemic of X days.

2024-03-11 11:47 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +## Modelling scenarios of epidemic response
That's a fair point; some reorganisation of the vignettes would indeed be useful. What I would propose is to merge this as is for now, and then to ask @avallecam to review the vignettes all together to see how they could be rationalised.

2024-03-11 12:58 UTC, jamesmbaazam commented on vignettes/modelling_scenarios.Rmd
> +duration <- max_time - with_seed(seed = 1, {
Okay, I see.

2024-03-11 13:00 UTC, jamesmbaazam commented on vignettes/modelling_scenarios.Rmd
> +It is not possible to pass lists of _populations_, _seasonality_, or _population changes_ (for the diphtheria model).
Yeah, it's good to leave it out for now even though people might want to model population change through birth-death processes, changing demographics, etc.

2024-03-11 13:02 UTC, pratikunterwegs commented
> ## Other comments
> 
> * In `.check_prepare_args_default()`, lots of subsetting are done in a pattern
>       that could potentially be turned into helper functions. Can subsetting
>       operations like `mod_args[["vaccination"]][["time_begin"]]` be combined into a
>       subsetting function that take an "intervention" and "element" argument?
>       This would reduce the hardcoding of the list elements and make the code more
>       readable and maintainable.
>
> * I see `get_parameter()` has been removed but I see the replaced subsetting
>       operations are identical to what `get_parameter()` would do. Why was it
>       removed instead of being updated to do the new list subsetting? Could you
>       convert all the `x$<some element>` into a getter function like `get_parameter()`
>       previously? This would make the code more readable.

Taking these two together as they're related - I felt `get_parameter()` wasn't offering much over inbuilt accessors. We have a preference for list-based S3 classes, so the `[[` accessor will likely remain robust. `get_parameter()` was also exported, which meant adding input checks, which I felt was making it slow down internal functions when it was used in them (as in `.check_prepare_args()`). Stripping those checks away for an internal-use version, say `.get_parameter()` did not seem to offer much more over `[[`. In `.check_prepare_args_*()` for example, `get_parameter()` use looks like `get_parameter(mod_args[["some element"]], "some member")`.

> * Can the details section of all the `check_args_*()` functions be combined
>       into a single template? They seem to be quite similar and repeated and might be
>       easier to maintain if turned into one.

Do you mean the overall documentation for these functions named `.check_prepare_args_*()`? They could be combined. The `Return` section would be quite long, since it would repeat elements a few times, once per model in case of slight differences.

> * Can the `R/dummy_elements.R` script be renamed to something more descriptive?
>       The `no_time_dependence()` function could be moved to the `time_dependence.R`
>       script and the `no_population_change()` function moved somewhere with related
>       content. This will make it easier to find the functions when needed.

I can return the dummy-elements functions to files that hold the classes and do away with this one.

> 
> * `output_to_df()` should probably be renamed to `output_to_dt()` since it
>       returns a `data.table`. The `return` value should also be changed from
>       `data.frame` to `data.table` to reflect the code.
> 

Thanks - I'll change the documented return type. I can rename this fn to `.output_to_table()`, as I'm not sure that we'll stick with `<data.table>`.

> * `epidemic_size()`:
>       
>  * The return value needs to be updated to say it returns a `data.table`.

Thanks, got it.

>  * Could you enhance it to return the epidemic size by a selection of age
>         groups?

This is a nice feature in theory, but in practice it may be good to restrict it to the current implementation. Demography groups in the `population` do not have to be named, but might be depending on the whether the demography vector or contact matrix have names. It might be easier for users to filter a resulting data.frame of demography group, time, and size, on the names of the demography group as shown in the column. I can add an issue for `epidemic_size()` to return a table-like rather than a vector.

>  * Could you return the "stage" as part of the output? I can easily imagine
>         that being useful in cases where a user wants to plot the epidemic size at
>         various stages of the outbreak.
>  * I would suggest renaming "stage" to timepoint or something similar and
>         filter by time instead of stage. We often think of epidemic timelines in
>         terms of dates and not stages. Using stages forces you to think in terms of
>         percentages of the whole timeline. Additionally, you could make "stage" an
>         optional argument alongside the new "time" argument.
> 

Yes to returning the stage as well as renaming it - collecting these feature requests in #190.

The reason `epidemic_size()` uses a percentage term is to quickly access e.g. the last size, the size at 50% time, etc., in a way that's agnostic to the actual time the epidemic runs. I can shift to a timepoint-based implementation (with optional `time`, returning final size by default) if that's more useful/more understandable. It would help to consider the expected output when a simulation does not run up to the requested time - should it error, or return a size of 0, or return `NA`, or return the last size available? Note that the last size might not be the 'final size' as an epidemic might not be complete by the simulation end time.

> * Is the term "demography_vector" chosen for any reason? I think in the contexts
>       it's used here, it mostly refers to the population size per age group.
>       Could you rename it to some like "group_pop_size" or something similar since
>       demography is too broad a term?

I think this was adopted from {finalsize}, which adopted it from earlier implementations. I think it's not too difficult to understand so unless there's a good reason to change it, I'll keep it to conform with {finalsize}.

> * Can `population_change` in `model_diphtheria()` be structured in a manner
>       to take a time series of population changes? For example, I might want to
>       model a population change that occurs at a certain time point and then another
>       change that occurs at a later time point. This would allow for more flexibility
>       in the model.

Yes; here's an example showing both increases and decreases in certain groups, t = 70, and t = 100:

```r
# the `values` list must always have as many elements as the `time` vector
# and each element of `values` must be of the same length as `demography_vector`
pop_change <- list(
  time = c(70, 100)
  values = list(
    change_1 = c(1e4, 1e5, 2e5),
    change_2 = c(-9e3, 1e3, -1e5)
  )
)
```

I considered adding this to the diphtheria vignette but this functionality might need more thinking through before a more detailed example is added.

> * Can `model_vacamole()` be renamed to `model_covid19()` or something
>       descriptive so as to align with the other models named after the disease they
>       represent? I can understand if you're trying to use the original
>       name to conserve the credit (or maybe I'm not privy to the reuse agreement)
>       but credit can be given in the function documentation and README as is currently
>       done.

It could indeed be. One reason I would not do that is that the philosophy of {epidemics} is now more towards collecting published models that can target types of diseases rather than specific diseases, e.g., the default model was recently used for a range of 11 diseases. Vacamole might be suitable for flu etc. as well, and the name refers to the two-dose leaky vaccination scenario with a vaccination-mediated infection pathway it implements, so I think it would be good to retain it.

>  * I would suggest doing the input checks outside of the `model_*()` functions
>       to make the code more focused on the model rather than being overpowered with
>       input checks.

Do you mean that in an analysis script users should run input checking on their arguments first, and then pass the checked arguments to model functions? I am not against that - it would certainly make the model functions lighter and more readable.

My feeling has been that users would appreciate self-contained functions more, where they only really have to create a `<population>` and pass it to a function which will do the rest. Passing a checked argument list would probably require adding `default_args_model_*()` functions, which users would have to modify to pass their own values. This is the approach [I've taken in [...]

2024-03-11 13:28 UTC, jamesmbaazam commented
> Thanks @jamesmbaazam for the feedback - happy to hear more on some of the points you've raised.
> 
> > ## Other comments
> > 
> > * In `.check_prepare_args_default()`, lots of subsetting are done in a pattern
> >   that could potentially be turned into helper functions. Can subsetting
> >   operations like `mod_args[["vaccination"]][["time_begin"]]` be combined into a
> >   subsetting function that take an "intervention" and "element" argument?
> >   This would reduce the hardcoding of the list elements and make the code more
> >   readable and maintainable.
> > * I see `get_parameter()` has been removed but I see the replaced subsetting
> >   operations are identical to what `get_parameter()` would do. Why was it
> >   removed instead of being updated to do the new list subsetting? Could you
> >   convert all the `x$<some element>` into a getter function like `get_parameter()`
> >   previously? This would make the code more readable.
> 
> Taking these two together as they're related - I felt `get_parameter()` wasn't offering much over inbuilt accessors. We have a preference for list-based S3 classes, so the `[[` accessor will likely remain robust. `get_parameter()` was also exported, which meant adding input checks, which I felt was making it slow down internal functions when it was used in them (as in `.check_prepare_args()`). Stripping those checks away for an internal-use version, say `.get_parameter()` did not seem to offer much more over `[[`. In `.check_prepare_args_*()` for example, `get_parameter()` use looks like `get_parameter(mod_args[["some element"]], "some member")`.

Thanks for the explanation. It makes sense to me

> > * Can the details section of all the `check_args_*()` functions be combined
> >   into a single template? They seem to be quite similar and repeated and might be
> >   easier to maintain if turned into one.
> 
> Do you mean the overall documentation for these functions named `.check_prepare_args_*()`? They could be combined. The `Return` section would be quite long, since it would repeat elements a few times, once per model in case of slight differences.

Yes, I meant the overall documentation. I suggested that after noticing the patterns, but it might not make sense to combine them.

> > * Can the `R/dummy_elements.R` script be renamed to something more descriptive?
> >   The `no_time_dependence()` function could be moved to the `time_dependence.R`
> >   script and the `no_population_change()` function moved somewhere with related
> >   content. This will make it easier to find the functions when needed.
> 
> I can return the dummy-elements functions to files that hold the classes and do away with this one.

Yes, it would make it easier to navigate the code base.

> > * `output_to_df()` should probably be renamed to `output_to_dt()` since it
> >   returns a `data.table`. The `return` value should also be changed from
> >   `data.frame` to `data.table` to reflect the code.
> 
> Thanks - I'll change the documented return type. I can rename this fn to `.output_to_table()`, as I'm not sure that we'll stick with `<data.table>`.

Alright.

> > * `epidemic_size()`:
> > * The return value needs to be updated to say it returns a `data.table`.
> 
> Thanks, got it.
> 
> > * Could you enhance it to return the epidemic size by a selection of age
> >   groups?
> 
> This is a nice feature in theory, but in practice it may be good to restrict it to the current implementation. Demography groups in the `population` do not have to be named, but might be depending on the whether the demography vector or contact matrix have names. It might be easier for users to filter a resulting data.frame of demography group, time, and size, on the names of the demography group as shown in the column. I can add an issue for `epidemic_size()` to return a table-like rather than a vector.
> 
> > * Could you return the "stage" as part of the output? I can easily imagine
> >   that being useful in cases where a user wants to plot the epidemic size at
> >   various stages of the outbreak.
> > * I would suggest renaming "stage" to timepoint or something similar and
> >   filter by time instead of stage. We often think of epidemic timelines in
> >   terms of dates and not stages. Using stages forces you to think in terms of
> >   percentages of the whole timeline. Additionally, you could make "stage" an
> >   optional argument alongside the new "time" argument.
> 
> Yes to returning the stage as well as renaming it - collecting these feature requests in #190.

Great

>  It would help to consider the expected output when a simulation does not run up to the requested time - should it error, or return a size of 0, or return `NA`, or return the last size available? 

It is often a difficult situation but sticking to a simple and easy-to-debug solution for now might do for a first pass. It can be improved with user feedback. I'm inclined to suggest returning the last size with a warning and some text on how to interpret it.

> Note that the last size might not be the 'final size' as an epidemic might not be complete by the simulation end time.

Wouldn't this be the case for `stage = 1` too?


> > * Is the term "demography_vector" chosen for any reason? I think in the contexts
> >   it's used here, it mostly refers to the population size per age group.
> >   Could you rename it to some like "group_pop_size" or something similar since
> >   demography is too broad a term?
> 
> I think this was adopted from {finalsize}, which adopted it from earlier implementations. I think it's not too difficult to understand so unless there's a good reason to change it, I'll keep it to conform with {finalsize}.
> 
> > * Can `population_change` in `model_diphtheria()` be structured in a manner
> >   to take a time series of population changes? For example, I might want to
> >   model a population change that occurs at a certain time point and then another
> >   change that occurs at a later time point. This would allow for more flexibility
> >   in the model.
> 
> Yes; here's an example showing both increases and decreases in certain groups, t = 70, and t = 100:
> 
> ```r
> # the `values` list must always have as many elements as the `time` vector
> # and each element of `values` must be of the same length as `demography_vector`
> pop_change <- list(
>   time = c(70, 100)
>   values = list(
>     change_1 = c(1e4, 1e5, 2e5),
>     change_2 = c(-9e3, 1e3, -1e5)
>   )
> )
> ```

Ah, nice!

> I considered adding this to the diphtheria vignette but this functionality might need more thinking through before a more detailed example is added.
> 
> > * Can `model_vacamole()` be renamed to `model_covid19()` or something
> >   descriptive so as to align with the other models named after the disease they
> >   represent? I can understand if you're trying to use the original
> >   name to conserve the credit (or maybe I'm not privy to the reuse agreement)
> >   but credit can be given in the function documentation and README as is currently
> >   done.
> 
> It could indeed be. One reason I would not do that is that the philosophy of {epidemics} is now more towards collecting published models that can target types of diseases rather than specific diseases, e.g., the default model was recently used for a range of 11 diseases. Vacamole might be suitable for flu etc. as well, and the name refers to the two-dose leaky vaccination scenario with a vaccination-mediated infection pathway it implements, so I think it would be good to retain it.

That makes sense for the generic models but there are other models named after diseases here as well. No?

> > * I would suggest doing the input checks outside of the `model_*()` functions
> >   to make the code more focused on the model rather than being overpowered with
> >   input checks.
> 
> Do you mean that in an analysis script users should run input checking on their arguments first, and then pass the checked arguments to model functions? I am not agai [...]

2024-03-11 13:53 UTC, pratikunterwegs commented
>>    Note that the last size might not be the 'final size' as an epidemic might not be complete by the simulation end time.

> Wouldn't this be the case for stage = 1 too?

Yes, it's simply the last size in the time series. Some user care is required in determining whether it is really the 'final size', after looking at the trajectory.

> That makes sense for the generic models but there are other models named after diseases here as well. No?

There are - we don't have good naming options for these. We have not made much progress in implementing more models, so general rules for model names have not really been developed.

2024-03-11 13:58 UTC, pratikunterwegs commented
>> Do you mean that in an analysis script users should run input checking on their arguments first, and then pass the checked arguments to model functions? I am not against that - it would certainly make the model functions lighter and more readable.

> Oh no, I see I didn't phrase that well. I meant that, for readability, you should consider bundling up the checks into helper functions as is done in our other packages like [simulist](https://github.com/epiverse-trace/simulist/blob/93d19271770d413cf20c518ef4ba4b4d29925dcd/R/sim_contacts.R#L57). But this might be a matter of style.

This could indeed be done. In {finalsize} some of the discussion were around how much to show this checking and preparation, and the idea was to strike a balance to prevent the codebase spreading over too many files. To some extent this is the role of the `.check_prepare_args_*()` functions.

2024-03-11 14:43 UTC, pratikunterwegs commented
>> Can the R/dummy_elements.R script be renamed to something more descriptive?
        The no_time_dependence() function could be moved to the time_dependence.R
        script and the no_population_change() function moved somewhere with related
        content. This will make it easier to find the functions when needed.

> I can return the dummy-elements functions to files that hold the classes and do away with this one.

These elements don't have a better place to go, as they are not classes.

2024-03-11 15:23 UTC, pratikunterwegs commented on R/check_args_diphtheria.R
> +  # assign initial state; note prop_vaccinated have been removed
Fixed in https://github.com/epiverse-trace/epidemics/pull/176/commits/09179e709f12ccaccd3dad1808f615696dbe508b

2024-03-11 15:24 UTC, pratikunterwegs commented on R/model_diphtheria.R
> +  # Check if parameters can be recycled;
Fixed in https://github.com/epiverse-trace/epidemics/pull/176/commits/09179e709f12ccaccd3dad1808f615696dbe508b

2024-03-11 15:25 UTC, pratikunterwegs commented on R/tools.R
> +    no_vaccination(population, doses = doses)
Fixed in https://github.com/epiverse-trace/epidemics/pull/176/commits/48eff2272241079c5677e88a82ba3200dac4aee3

2024-03-11 15:27 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +library(EpiEstim)
Fixed in https://github.com/epiverse-trace/epidemics/pull/176/commits/c2e02eaf58b3f176ae5c8cf444c12731ae9e1f59

2024-03-11 15:27 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +Since _EpiEstim_ estimates $Rt$, the real-time $R$, we shall use the mean of the estimates over the time period, and the mean of the standard deviation, as parameters for a distribution from which to
Fixed in https://github.com/epiverse-trace/epidemics/pull/176/commits/c2e02eaf58b3f176ae5c8cf444c12731ae9e1f59

2024-03-11 15:30 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +2. All but one infection parameter must be scalar values (single numbers). This is the worked-out example shown above.
Rephrased in https://github.com/epiverse-trace/epidemics/pull/176/commits/ef0e9737b0e5de5e5db4aa2a2eee425e4de27273 to "... can accept multiple infection parameters as vectors, so long as any vectors are all of the same length, or of length 1 (scalar values) ..."

2024-03-11 15:31 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +duration <- max_time - with_seed(seed = 1, {
Added in https://github.com/epiverse-trace/epidemics/pull/176/commits/ef0e9737b0e5de5e5db4aa2a2eee425e4de27273

2024-03-11 15:31 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +    size = map_dbl(data, epidemic_size, by_group = FALSE)
Added in https://github.com/epiverse-trace/epidemics/pull/176/commits/ef0e9737b0e5de5e5db4aa2a2eee425e4de27273

2024-03-11 15:34 UTC, pratikunterwegs commented on R/model_vacamole.R
> +  })]
I hesitate to add more functions and expand the namespace although it would indeed make for DRY-er code - will leave this for now.

My main concern about this code was actually whether it's less efficient to use it within a data.table, than to create a standalone list and then assign it to a list-column - any thoughts on that?

2024-03-11 15:44 UTC, pratikunterwegs commented on R/model_vacamole.R
>    )
I'm going to leave this one for now, as combining the two parts don't really mesh well with the other `.cross_check_*()` functions, which don't include an assert on the class

2024-03-11 15:45 UTC, pratikunterwegs commented on R/model_vacamole.R
>    )
Thanks - I'll open an issue on rationalising the input checking and cross-checking functions.

2024-03-12 12:28 UTC, pratikunterwegs commented on R/model_vacamole.R
>    )
For now, this is addressed with better comments in https://github.com/epiverse-trace/epidemics/pull/176/commits/51cccaf5f301afa9b2341b7d54b208b4a9e396c0

2024-03-12 12:28 UTC, jamesmbaazam commented on R/model_vacamole.R
> +  })]
> My main concern about this code was actually whether it's less efficient to use it within a data.table, than to create a standalone list and then assign it to a list-column - any thoughts on that?

I'm not sure unless we run some benchmarks but at first glance, the current implementation ticks all the boxes for performance: vectorisation with `Map()` within a `data.table()`.

2024-03-12 12:28 UTC, pratikunterwegs commented on R/model_diphtheria.R
> +  is_lofls <- checkmate::test_list(
Leaving the name for now as it's internal, but have addressed with better comments in https://github.com/epiverse-trace/epidemics/pull/176/commits/51cccaf5f301afa9b2341b7d54b208b4a9e396c0

2024-03-12 12:29 UTC, pratikunterwegs commented on R/model_diphtheria.R
> +  is_lofints <- checkmate::test_list(
Leaving the name for brevity, but have made the comments more explanatory in https://github.com/epiverse-trace/epidemics/pull/176/commits/51cccaf5f301afa9b2341b7d54b208b4a9e396c0

2024-03-12 12:30 UTC, pratikunterwegs commented on R/model_diphtheria.R
>    )
Added comments in https://github.com/epiverse-trace/epidemics/commit/51cccaf5f301afa9b2341b7d54b208b4a9e396c0

2024-03-12 12:35 UTC, pratikunterwegs commented
Thanks both @jamesmbaazam and @adamkucharski for your reviews. @CarmenTamayo, you mentioned you might have some feedback as well, would you like to add it? Otherwise I think this PR is ready to merge.

2024-03-12 12:54 UTC, CarmenTamayo commented
> Thanks both @jamesmbaazam and @adamkucharski for your reviews. @CarmenTamayo, you mentioned you might have some feedback as well, would you like to add it? Otherwise I think this PR is ready to merge.

Hi @pratikunterwegs I provided some feedback as well, specifically for the new vignette for modelling parameter uncertainty, can you see my comments? I did this last week

2024-03-12 12:57 UTC, CarmenTamayo reviewed
Sorry Pratik, I had pending comments but hadn't actually submitted them

2024-03-12 13:04 UTC, pratikunterwegs commented
> Sorry Pratik, I had pending comments but hadn't actually submitted them

Thanks! I remembered you'd asked me questions about some parts of this PR so I knew there must be comments somewhere!

2024-03-12 13:07 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +
Updated by Adam to read

"Uncertainty in the characteristics of an epidemic is a key element and roadblock in epidemic response [@shea2020]. Epidemic dynamics can be influenced by two main sources of uncertainty: intrinsic randomness in the transmission process, and uncertain knowledge of the parameters underlying the transmission process. Here we focus on the latter, i.e. uncertainty in the input parameters of an epidemic model."

2024-03-12 13:37 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +### Output type for vector parameter inputs
Could you explain what you mean by naming the sections? Some of the text is inline, explaining the output, while the details are in the box.

2024-03-12 13:44 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +### Passing vectors of epidemic duration
The durations are drawn from a distribution of epidemic start times, reflecting that there is uncertainty in when the epidemic will start over a fixed time period (similar to the Gaza projections work). This is different from the scenarios section which more focused on policy options.

2024-03-12 13:45 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +2. All but one infection parameter must be scalar values (single numbers). This is the worked-out example shown above.
This has been changed following James' feedback to "_epidemics_ model functions can accept multiple infection parameters as vectors, so long as any vectors are all of the same length, or of length 1 (scalar values) as shown below." And it is above the code.

2024-03-12 13:47 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +It is not possible to pass lists of _populations_, _seasonality_, or _population changes_ (for the diphtheria model).
No, sorry this was unclear - this is not possible for any model, and only the diphtheria model accepts the `population_change` argument. Changed to "It is not currently possible to pass lists of _populations_, _seasonality_, or _population changes_ to any models."

2024-03-13 11:18 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +intervention_duration <- 200
Fixed inhttps://github.com/epiverse-trace/epidemics/pull/176/commits/8c26a986d4a4dca2568cf15c0a97f34bd643f81d

2024-03-13 11:19 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +It is not possible to pass lists of _populations_, _seasonality_, or _population changes_ (for the diphtheria model).
Fixed in https://github.com/epiverse-trace/epidemics/pull/176/commits/8c26a986d4a4dca2568cf15c0a97f34bd643f81d

2024-03-13 11:19 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +### Obtaining and passing a vector of infection parameters
Added more explanation in https://github.com/epiverse-trace/epidemics/pull/176/commits/8c26a986d4a4dca2568cf15c0a97f34bd643f81d

2024-03-13 11:19 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +The code to set up a population is hidden here, but is similar to that found in the ["Getting started with epidemic scenario modelling components"](epidemics.html) vignette, and models the U.K. popul
Changed in https://github.com/epiverse-trace/epidemics/pull/176/commits/8c26a986d4a4dca2568cf15c0a97f34bd643f81d

2024-03-13 11:20 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +For this example, we consider influenza with pandemic potential [@ghani2010], and prepare multiple samples of the estimated $R$.
Added in https://github.com/epiverse-trace/epidemics/pull/176/commits/8c26a986d4a4dca2568cf15c0a97f34bd643f81d

2024-03-13 11:20 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +  ggplot() +
Added in https://github.com/epiverse-trace/epidemics/pull/176/commits/8c26a986d4a4dca2568cf15c0a97f34bd643f81d

2024-03-14 10:18 UTC, pratikunterwegs commented on vignettes/modelling_scenarios.Rmd
> +### Combinations of intervention and vaccination scenarios
Opened #194 to address this.

2024-03-14 10:20 UTC, pratikunterwegs commented
Thanks all for your reviews - merging this now so we can make smaller PRs in future for related issues.

2024-03-14 10:21 UTC, merged