Add developer side walkthrough
epiverse-trace/epidemics pull request #210
Opened 2024-03-26 12:20 UTC by pratikunterwegs

This PR aims to fix #193 by adding a developer side walkthrough vignette that lays out how to make some quick edits to the ODE models.

2024-03-28 07:50 UTC, sbfnk requested changes
Thanks, I think this will be really useful for people wanting to make changes to the model(s). I left a few comments where I stumbled across things.

Can you add a section "how to add a new model"? I.e. should I start with copying the default model and then take it from there?

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +Have you modified an existing model to cover new use cases or disease types? We welcome contributions of new model structures. Examples include models targeting vector borne diseases, or diseases wit
```suggestion
Have you modified an existing model to cover new use cases or disease types? We welcome contributions of new model structures. Examples include models targeting vector borne diseases, or diseases with a sylvatic cycle. Please get in touch via a GitHub [Issue](https://github.com/epiverse-trace/epidemics/issues)!
```

There's no discussion board, right?

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +
I'd find the vignette easier to follow if there was a first section "Adding/removing parameters" with this content, then making them time-dependent, then changing flows.

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +2. Next, modify the C++ function arguments in `src/model_*.cpp` so that any newly added rate parameters can be passed from R to C++. Typically, single parameters should be passed by reference as `con
How would one add parameters of dimension >1 (e.g. age-dependent)?

I later found it below. Perhaps link to that section later?

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +## Modifying which parameters can be time dependent
Before that can we have a small section "where to find the model" describing the file/directory structure (as models are spread across multiple directories)?

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +dxdt.col(0) = B -sToE - sToV;  // B -β*S*contacts*I - ν
Can you show what the line looked like before and clarify that this shows the ODE for the number of susceptibles (just so people don't think this is a new line to be added). I.e. in the previous section (with the header one level higher) could say: "In the following, we will consider a number of modifications to the susceptible compartment, which we assume to be given by...".

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +Define birth rate and background mortality rate parameters (denoted $b$ and $d$ respectively), and modify the compartmental transitions as follows. This example shows only the equations for the susce
```suggestion
Define birth rate and background mortality rate parameters (denoted $B$ and $D$ respectively), and modify the compartmental transitions as follows. This example shows only the equations for the susceptible compartment.
```

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +    // define a birth rate
```suggestion
    // define a per-capita birth rate
```

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +    Eigen::ArrayXd births(4);  // hardcoded for four age groups
why not call it `B` as in the example above? Or is this something else?

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +    // calculate number of births
```suggestion
    // calculate total birth rate
```
just sticking with the terminology from above

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +    const Eigen::ArrayXd all_inflows = births + immigration;
and then replace `B` with `all_inflows` in line 101?

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +// note x.col(3).array() is the vector of age-specific recovereds
why is this 3? Is this defined somewhere?

2024-03-28 07:50 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +_epidemics_ treats vaccination as special process that requires a composable element in the form of an S3 class, `<vaccination>`, which allows defining time-limited, group-specific vaccination rates
And I can't make these time-limited rates different at different times, right?

2024-03-28 07:51 UTC, sbfnk commented on vignettes/developer-walkthrough.Rmd
> +Vaccination is only strictly allowed in the ODE models 'default' and 'Vacamole', and these are covered here. Begin by dismantling the model code to remove any functionality related to the `<vaccinati
Should we just define a default model with and one without vaccination?

2024-03-28 09:18 UTC, pratikunterwegs commented
Thanks @sbfnk - agree with all. Will wait perhaps a week or two in case more feedback comes in.

2024-04-05 10:50 UTC, adamkucharski commented on vignettes/developer-walkthrough.Rmd
> +## Modifying which parameters can be time dependent
Agree – having this at the start to orientate contributors would be very helpful, i.e. how `R/model_default.R`, `R/check_args_default.R`, `src/model_default.cpp`,  `inst/include/model_default.h` link together with the `model_default()` function call.

2024-04-09 10:30 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +// note x.col(3).array() is the vector of age-specific recovereds
It's hardcoded as the column holding the recovered; this has been added to the model header file.

2024-04-09 10:35 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +_epidemics_ treats vaccination as special process that requires a composable element in the form of an S3 class, `<vaccination>`, which allows defining time-limited, group-specific vaccination rates
That's right, but this section shows how to remove this functionality and implement a uniform vaccination rate that could be targeted with the time-dependence functionality to make the rate different at different times.

2024-04-09 10:37 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +Vaccination is only strictly allowed in the ODE models 'default' and 'Vacamole', and these are covered here. Begin by dismantling the model code to remove any functionality related to the `<vaccinati
I would hesitate to do that as one can get a no-vaccination model by simply not passing a `<vaccination>` to the model. Adding another model with such a small difference would add to the package code without substantial gain in functionality.

2024-04-09 10:37 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +    const Eigen::ArrayXd all_inflows = births + immigration;
Yes, added.

2024-04-09 10:38 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +    Eigen::ArrayXd births(4);  // hardcoded for four age groups
Agreed, but then thought I should have clearly named variables even in this dummy example.

2024-04-09 13:19 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +Have you modified an existing model to cover new use cases or disease types? We welcome contributions of new model structures. Examples include models targeting vector borne diseases, or diseases wit
Added in https://github.com/epiverse-trace/epidemics/pull/210/commits/d0646b6d71f2e1f5624db04db670c0b48dbe575f

2024-04-09 13:19 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +
Added in https://github.com/epiverse-trace/epidemics/pull/210/commits/8085ddef0037c295895ad630cd8af8fed8cae5a2. I've moved the sections around a bit, hopefully more understandable now

2024-04-09 13:21 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +## Modifying which parameters can be time dependent
Added a directory tree with comments that hopefully explains this in https://github.com/epiverse-trace/epidemics/pull/210/commits/4df85c0b353332bffbbad56fb17108303c3c477f

2024-04-09 13:21 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +dxdt.col(0) = B -sToE - sToV;  // B -β*S*contacts*I - ν
Added in https://github.com/epiverse-trace/epidemics/pull/210/commits/440ad2e49dbeb9f63fe1477fbc876f0924a12d0d

2024-04-09 13:21 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +Define birth rate and background mortality rate parameters (denoted $b$ and $d$ respectively), and modify the compartmental transitions as follows. This example shows only the equations for the susce
Changed this a bit in https://github.com/epiverse-trace/epidemics/pull/210/commits/440ad2e49dbeb9f63fe1477fbc876f0924a12d0d, hope it makes sense

2024-04-09 13:22 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +    // define a birth rate
Fixed in https://github.com/epiverse-trace/epidemics/pull/210/commits/440ad2e49dbeb9f63fe1477fbc876f0924a12d0d

2024-04-09 13:22 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +    // calculate number of births
Fixed in https://github.com/epiverse-trace/epidemics/pull/210/commits/440ad2e49dbeb9f63fe1477fbc876f0924a12d0d I think - but do say if terminology is wrong

2024-04-09 13:34 UTC, pratikunterwegs commented on vignettes/developer-walkthrough.Rmd
> +2. Next, modify the C++ function arguments in `src/model_*.cpp` so that any newly added rate parameters can be passed from R to C++. Typically, single parameters should be passed by reference as `con
Added links to this section

2024-04-09 13:36 UTC, pratikunterwegs commented
Thanks @sbfnk and @adamkucharski for taking a look at this. I've pushed changes that show the minimal package structure, and a section on adding and removing parameters. Hope this makes it easier to read. I'm aiming to merge this by the end of the week.

2024-04-15 16:36 UTC, alxsrobert commented
Hi Pratik, Adam asked me last week to have a look at the developer vignette for the perspective of someone who is not very familiar with the package (so I've also looked at the "design decision" vignette to understand the structure of epidemics). I've written a few notes. Overall I thought the vignette was clear and well-designed, but I thought of some clarifications:
- I think that the  "guide to package structure" section in the developer walkthrough does not make sense to someone who is not already quite familiar with the package:
  - Some explanations of the files do not really make sense to me ("functions to construct cross-checking fns", "MODEL FUNC WRAPPING ODE SYSTEM; LEVEL 2")
  - The levels are not yet defined and therefore appear confusing.
  - I would suggest removing the mentions of scripts that are not mentioned in this vignette (so have a "simplified" structure, and maybe have the full structure at the end of the vignette, where there can be a slightly longer description of each file ). And introduce what the levels correspond to before the package structure.
- Similarly, in the "design decisions"  vignette, I would put figure 1 and 2 (so the "package architecture" section) after the definitions of some terms and broad concepts:
  - Figure 2 is quite overwhelming, so I didn't really know what I was meant to look for and take from it. I was also wondering what terms like "composable elements" from Figure 1 meant, only to have it defined at the next section, it would be better if it was defined before the figure (or right after it). 
  - I would suggest adding a few sentences explaining what the figure is for / what we should look at. Maybe also splitting Figure 2 into multiple figures?
- I think the section "adding or removing parameter" could do with some example code for each subsection. For instance, "Modify the compartmental transitions in the FunctionObject ODE model inst/include/model_*.h appropriately to include the mortality rate" seems unclear to me, does that just refer to adding / removing an extra argument? Having the description without the example makes it sound complicated, while if I understand well each step requires little re-coding (for a simple example).
- I think the sections with examples are good and clear. It would be good to remind the reader in what script each snippet of code is added (I think they are mentioned in the "Modifying compartmental flow..." section heading, but it would be clearer if it was repeated here).
- I'm don't think that every single section needs a specific example, but in my opinion the vignette should start with walk-through examples (like in "modelling birth"/ "modelling waning immunity"), so the reader would start with simple code, and become more familiar with the structure, before sections that just feature explanations.

I hope this is helpful, let me know if anything is unclear!

2024-04-16 07:58 UTC, pratikunterwegs commented
Thanks @alxsrobert - all helpful suggestions that I'll incorporate as edits to this document.

2024-05-30 09:11 UTC, merged